Repository cloudforet-io/console-api-v2, pull requests merged in 2023-01, with the labels that each got.

#29 Modify grpc method name in interface
  src/cloudforet/console_api_v2/interface/rest/cost_analysis/budget_usage.py
  src/cloudforet/console_api_v2/interface/rest/cost_analysis/cost.py
Labels: enhancement

#30 add settings field in CustomWidget
  src/cloudforet/console_api_v2/model/dashboard/custom_widget.py
Labels: enhancement

#31 Update some part of inventory api docs
  src/cloudforet/console_api_v2/interface/rest/inventory/change_history.py
  src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service.py
  src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_tag.py
  src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_type.py
  src/cloudforet/console_api_v2/interface/rest/inventory/region.py
  src/cloudforet/console_api_v2/model/__init__.py
  src/cloudforet/console_api_v2/model/inventory/__init__.py
  src/cloudforet/console_api_v2/model/inventory/change_history.py
  src/cloudforet/console_api_v2/model/inventory/cloud_service.py
  src/cloudforet/console_api_v2/model/inventory/cloud_service_tag.py
  src/cloudforet/console_api_v2/model/inventory/cloud_service_type.py
  src/cloudforet/console_api_v2/model/inventory/note.py
  src/cloudforet/console_api_v2/model/inventory/region.py
Labels: documentation

#33 Modify ip_address name and type in Inventory.cloud_service
  src/cloudforet/console_api_v2/model/inventory/cloud_service.py
Labels: documentation

#32 Remove auth from identity apis
  src/cloudforet/console_api_v2/interface/rest/identity/domain.py
  src/cloudforet/console_api_v2/interface/rest/identity/token.py
Labels: enhancement

#35 Modify labels field type dict -> list
  src/cloudforet/console_api_v2/model/dashboard/domain_dashboard.py
Labels: bug

#36 Modify cost apis description
  src/cloudforet/console_api_v2/interface/rest/cost_analysis/cost.py
  src/cloudforet/console_api_v2/model/cost_analysis/__init__.py
  src/cloudforet/console_api_v2/model/cost_analysis/cost.py
Labels: documentation

#37 Modify identity apis description
  src/cloudforet/console_api_v2/conf/global_conf.py
  src/cloudforet/console_api_v2/interface/rest/identity/project.py
  src/cloudforet/console_api_v2/interface/rest/identity/token.py
  src/cloudforet/console_api_v2/interface/rest/identity/user.py
  src/cloudforet/console_api_v2/model/identity/token.py
Labels: documentation

#39 Modify inventory apis description
  src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service.py
  src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_type.py
  src/cloudforet/console_api_v2/interface/rest/inventory/region.py
Labels: documentation

#41 add tag_keys field in model of CloudService and remove CloudServiceTags
  src/cloudforet/console_api_v2/conf/router_conf.py
  src/cloudforet/console_api_v2/interface/rest/inventory/cloud_service_tag.py
  src/cloudforet/console_api_v2/model/inventory/cloud_service.py
  src/cloudforet/console_api_v2/model/inventory/cloud_service_tag.py
Labels: enhancement

#40 Separating service by app
  src/cloudforet/console_api_v2/conf/global_conf.py
  src/cloudforet/console_api_v2/conf/router_conf.py
  src/cloudforet/console_api_v2/model/inventory/cloud_service.py
Labels: enhancement

#42 Remove deprecated router
  src/cloudforet/console_api_v2/conf/router_conf.py
Labels: enhancement
